### ISSUE TITLE
Keeps prior connection info after shutting down services

### ISSUE THREAD

**Issue by ctalbotSFDC** [anandbn/mdata-docker#9]
When I close all services, then restart them -- even if I don't go to localhost:3000, it will pick up the last connection I had and start running again.  If the session has timed out with that connection, it gives me:

```
mdata-worker_1  | 2020-06-09T13:42:12.865Z [mdata-worker] info: Received request to index org ... 
mdata-worker_1  | logFileName:logs/sfdc-utils.log
mdata-worker_1  | (node:1) UnhandledPromiseRejectionWarning: INVALID_SESSION_ID: Session expired or invalid
mdata-worker_1  |     at HttpApi.getError (/app/node_modules/jsforce/lib/http-api.js:250:13)
mdata-worker_1  |     at /app/node_modules/jsforce/lib/http-api.js:95:22
mdata-worker_1  |     at tryCallOne (/app/node_modules/promise/lib/core.js:37:12)
mdata-worker_1  |     at /app/node_modules/promise/lib/core.js:123:15
mdata-worker_1  |     at flush (/app/node_modules/asap/raw.js:50:29)
mdata-worker_1  |     at processTicksAndRejections (internal/process/task_queues.js:79:11)
mdata-worker_1  | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
mdata-worker_1  | (node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

It's frustrating since if I was opening the app to connect to a new environment, and this fires before I load localhost:3000 & do the connection, then I get an error & have to stop / restart all the services again -- it stops doing anything past logging the payload error

**Comment by anandbn** [comment]
I'm planning to migrate much of this over to nest.js vs. bare bones expressJS for better code maintainability.
